name: SurvivalAPI
main: net.samagames.survivalapi.SurvivalPlugin
version: 1.0

depend: [WorldEdit]
softdepend: [SamaGamesAPI, ShadowsAPI]

load: STARTUP

author: BlueSlime
website: http://blueslime.fr

commands:
  uhc:
    description: Team manager
    usage: /uhc

  nextevent:
    description: Fire next event
    usage: /nextevent
    permission: sg.op
    permission-message: Permission non accordée