name: SurvivalAPI
main: net.samagames.survivalapi.SurvivalPlugin
version: 1.0

depend: [WorldEdit]
softdepend: [SamaGamesAPI]

load: STARTUP

author: BlueSlime
website: http://blueslime.fr

commands:
   uhc:
      description: Gestion d'équipe
      usage: /uhc